CREATE TABLE USERS(
    USERNAME VARCHAR2(50),
    PASSWORD VARCHAR2(50) NOT NULL,
    ENABLED CHAR(1) DEFAULT '1',
    PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES(
    USERNAME VARCHAR2(50) NOT NULL,
    AUTHORITY VARCHAR2(50) NOT NULL
);

ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);

CREATE UNIQUE INDEX IDX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY); 

INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('USER00','1234');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('MEMBER00','1234'); 
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('ADMIN00','1234');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('USER00','ROLE_USER'); 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('MEMBER00','ROLE_MEMBER'); 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('ADMIN00','ROLE_MEMBER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('ADMIN00','ROLE_ADMIN');

SELECT * FROM AUTHORITIES;
SELECT * FROM USERS;

DELETE FROM USERS;
DELETE FROM AUTHORITIES;

COMMIT; 

CREATE TABLE SECURITYMEMBER (
    NO NUMBER,
    ID VARCHAR2(50) NOT NULL,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    COIN NUMBER(10)DEFAULT 0,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    ENABLED CHAR(1) DEFAULT '1',
    PRIMARY KEY (NO)
);

CREATE TABLE SECURITYMEMBER_AUTH (
NO NUMBER NOT NULL,
AUTH VARCHAR2(50) NOT NULL
);

ALTER TABLE SECURITYMEMBER_AUTH ADD CONSTRAINT SECURITYMEMBER_AUTH_FK FOREIGN KEY (NO) REFERENCES SECURITYMEMBER(NO);

CREATE SEQUENCE SECURITYMEMBER_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES (SECURITYMEMBER_SEQ.NEXTVAL, 'MEMBER0','$2a$10$ohA1zfwg.el0qEbcUisAtOwfEM/Q0XikaQqzLF4RLvvlQBHjNhkUG','회원0');
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES (SECURITYMEMBER_SEQ.NEXTVAL, 'MEMBER1','$2a$10$0YeNJZi0ZpHNJ962vF4KbOPbiiAW/FWaIOu8PTypWyzKnqmHDXEbe','회원1');
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES (SECURITYMEMBER_SEQ.NEXTVAL, 'MEMBER2','$2a$10$q8SAiCddta4vsxze3klZKOWWLoo1qwgwTQ7MdBcN3ZV8oL435vszm','회원2');
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES (SECURITYMEMBER_SEQ.NEXTVAL, 'ADMIN3','$2a$10$tu7hm6.6uYkcvMi//ol9A.gLeyGFwezZmtlSnvgUeBhgZ1UaSN1CG','관리자3');
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES (SECURITYMEMBER_SEQ.NEXTVAL, 'ADMIN4','$2a$10$SAipGDDRGkCStRyrao.pPeseuMoeBFiifUH0RAFDyyb.p/WG59zuS','관리자4');

INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER WHERE ID = 'MEMBER0'),'ROLE_MEMBER');
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER WHERE ID = 'MEMBER1'),'ROLE_MEMBER');
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER WHERE ID = 'MEMBER2'),'ROLE_MEMBER');
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER WHERE ID = 'ADMIN3'),'ROLE_ADMIN');
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER WHERE ID = 'ADMIN4'),'ROLE_ADMIN');
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER WHERE ID = 'ADMIN4'),'ROLE_MEMBER');

SELECT * FROM SECURITYMEMBER;
SELECT * FROM SECURITYMEMBER_AUTH;

COMMIT;

SELECT * FROM SECURITYMEMBER WHERE ID = 'MEMBER0';
SELECT B.ID, A.AUTH FROM SECURITYMEMBER_AUTH A, SECURITYMEMBER B WHERE A.NO = B.NO AND B.ID = 'ADMIN4';

CREATE TABLE PERSISTENT_LOGINS (
USERNAME VARCHAR2(64) NOT NULL,
SERIES VARCHAR2(64) NOT NULL,
TOKEN VARCHAR2(64) NOT NULL,
LAST_USED DATE NOT NULL,
PRIMARY KEY (SERIES)
);

SELECT * FROM PERSISTENT_LOGINS;