CREATE TABLE CART(
    CART_ITEM_NO NUMBER PRIMARY KEY,
    P_NO VARCHAR2(30) NOT NULL,
    P_QTY NUMBER NOT NULL,
    P_PRICE NUMBER NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL
);
ALTER TABLE SALES ADD CONSTRAINT FOREIGN KEY(P_NO) REFERENCES PRODUCT(P_NO);
    
CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM PRODUCT;
SELECT * FROM CATEGORY;
SELECT * FROM S_CATEGORY;
SELECT * FROM CART;

SELECT * FROM PRODUCT;

SELECT A.P_NAME, SUM(A.P_QTY) FROM PRODUCT A, PRODUCT B GROUP BY A.P_NAME;

SELECT P_NAME, SUM(P_QTY) FROM PRODUCT GROUP BY P_NAME;

SELECT ROWNUM, C.C_NO, S.S_NO, P.P_NAME, P.P_QTY, P.P_EXPDATE FROM PRODUCT P, CATEGORY C, S_CATEGORY S WHERE P.P_SUBCATEGORY_NO = S.S_NO AND S.C_NO = C.C_NO ORDER BY S.S_NO;

SELECT * FROM PRODUCT ORDER BY P_SUBCATEGORY_NO;

SELECT P.P_NO, P.P_NAME, P.P_PRICE, P.P_QTY, P.P_EXPDATE, C.C_NAME, S.S_NAME FROM PRODUCT P, S_CATEGORY S, "CATEGORY" C
WHERE P.P_SUBCATEGORY_NO = S.S_NO
AND S.C_NO = C.C_NO ORDER BY P.P_NO;

SELECT * FROM PRODUCT ORDER BY P_CATEGORY_NO;

SELECT * FROM CART;