CREATE TABLE BOARD(
    BOARD_NO NUMBER,                -- PK
    TITLE VARCHAR2(20) NOT NULL CHECK(REGEXP_LIKE(TITLE, '^[가-힣]{3,20}$')),   -- 한글만, 최소 3자, 최대 20자
    CONTENT CHAR(1000) NOT NULL,    -- 최대 1000자
    WRITER VARCHAR2(50) NOT NULL CHECK(REGEXP_LIKE(WRITER, '^[가-힣A-Za-z]{2,10}$')),-- 한글 + 알파벳 혼합 구성, 최소 2자, 최대 10자
    REG_DATE DATE DEFAULT SYSDATE   -- 날짜 형식으로 입력, 미지정시 현재 시각으로 자동 저장
);
ALTER TABLE BOARD ADD CONSTRAINTS BOARD_PK PRIMARY KEY (BOARD_NO);

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;

    -- GENDER CHAR(1) NOT NULL CHECK(GENDER IN ('M','F')),
    -- SCORE NUMBER(3) NOT NULL CHECK(SCORE BETWEEN 0 AND 100),