-- SUBJECT 테이블 생성
CREATE TABLE SUBJECT(
    NO NUMBER NOT NULL,
    S_NUM VARCHAR(2) NOT NULL,
    S_NAME VARCHAR2(24) NOT NULL,
    PRIMARY KEY(NO),
    UNIQUE(S_NUM)
);

-- 일련번호(NO) 자동증가 시퀀스 생성
CREATE SEQUENCE SUBJECT_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM SUBJECT;

-- LESSON 테이블 생성
CREATE TABLE LESSON(
    NO NUMBER NOT NULL,
    L_ABBRE VARCHAR2(2) NOT NULL,
    L_NAME VARCHAR2(20) NOT NULL,
    PRIMARY KEY(NO),
    UNIQUE(L_ABBRE)
);

-- 일련번호(NO) 자동증가 시퀀스 생성
CREATE SEQUENCE LESSON_SEQ
START WITH 1
INCREMENT BY 1;

-- STUDENT 테이블 생성
CREATE TABLE STUDENT( 
    NO NUMBER NOT NULL,
    SD_NUM VARCHAR2(8) NOT NULL,
    SD_NAME VARCHAR2(12) NOT NULL,
    SD_ID VARCHAR2(12) NOT NULL,
    SD_PASSWD VARCHAR2(12) NOT NULL,
    S_NUM VARCHAR2(2) NOT NULL,
    SD_BIRTHDAY VARCHAR2(8) NOT NULL,
    SD_PHONE VARCHAR2(15) NOT NULL,
    SD_ADDRESS VARCHAR2(80) NOT NULL,
    SD_EMAIL VARCHAR2(40) NOT NULL,
    SD_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_PK PRIMARY KEY(NO);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_NUM_UK UNIQUE (SD_NUM);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_ID_UK UNIQUE(SD_ID);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_SUBJECT_FK FOREIGN KEY(S_NUM) REFERENCES SUBJECT(S_NUM)ON DELETE SET NULL;

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1;
SELECT STUDENT_SEQ.NEXTVAL FROM DUAL;

select * from student;