-- Q1. EMPLOYEES 테이블의 모든 내용 출력
SELECT * FROM EMPLOYEES;

-- Q2. 사원의 이름, 급여, 입사일자 정보를 출력
SELECT FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES;

-- Q4. EMPLOYEES 이름, 직급 출력(ex. "ELLEN님의 직급은  매니저 입니다.")
SELECT FIRST_NAME || '님의 직급은' || JOB_ID || '입니다.' AS MESSAGE FROM EMPLOYEES;

-- Q5. EMPLOYEES 직급 출력(중복 제외)
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

-- Q6-1. EMPLOYEES 테이블에서 부서번호가 110번인 직원에 관한 모든 정보 출력
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 110;

-- Q6-2. EMPLOYEES 테이블에서 급여가 5000 미만이 되는 직원
SELECT * FROM EMPLOYEES WHERE SALARY < 5000;

-- Q6-3. 이름이 John인 사람의 직원번호, 직원명, 직급을 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID FROM EMPLOYEES WHERE FIRST_NAME = 'John';

-- Q7-1. 급여가 5000이상, 10000이하인 직원 정보 출력
SELECT * FROM EMPLOYEES WHERE SALARY >= 5000 AND SALARY <=10000;

-- Q7-2. 직원번호가 134 또는 201 또는 107인 직원 정보 출력
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 134 OR EMPLOYEE_ID = 201 OR EMPLOYEE_ID = 107;

-- Q7-3. 직급이 FI_MGR가 아닌 직원 정보 출력
SELECT * FROM EMPLOYEES WHERE NOT JOB_ID = 'FI_MGR';

-- Q7-4. 급여가 2500이상, 4500이하인 직원의 직원번호, 이름, 급여를 출력(AND 연산자와 BETWEEN AND 연산자를 각각 사용하여 2개 모두 만들기)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY >= 2500 AND SALARY <= 4500;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY BETWEEN 2500 AND 4500;

-- Q7-5. 커미션비율이 0.3 또는 0.05 또는 0.1 중 하나인 직원의 직원번호, 이름, 급여, 커미션 비율 정보를 출력(OR 연산자와 IN 연산자를 각각 사용하여 2개 모두 만들기)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT = 0.3 OR COMMISSION_PCT = 0.05 OR COMMISSION_PCT = 0.1;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IN(0.3, 0.1, 0.05);

-- Q8. 이름에 a를 포함하지 않는 직원의 직원번호, 이름 정보를 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE NOT FIRST_NAME LIKE '%a%' AND NOT FIRST_NAME LIKE '%A%';

-- Q9. 자신의 직속상관이 없는 직원의 전체 이름, 직급, 직원번호 정보를 출력
SELECT FIRST_NAME, LAST_NAME, JOB_ID, EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL; 

-- Q10-1. 직원번호, 이름, 급여 정보를 급여가 높은 순으로 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

-- Q10-2. 입사일이 가장 최근인 직원 순으로 직원번호, 이름, 입사일 정보를 출력
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES ORDER BY HIRE_DATE DESC;
