CREATE TABLE CART(
    CART_ITEM_NO NUMBER PRIMARY KEY,
    P_NO VARCHAR2(30) NOT NULL,
    P_QTY NUMBER NOT NULL,
    P_PRICE NUMBER NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL
);
ALTER TABLE SALES ADD CONSTRAINT FOREIGN KEY(P_NO) REFERENCES PRODUCT(P_NO);
    
    
    
ALTER TABLE CART ADD DEL_YN NUMBER(1) DEFAULT NULL;
ALTER TABLE CART ADD RECEIPT_NO NUMBER DEFAULT NULL;
ALTER TABLE CART ADD PAYMENT_DAY DATE DEFAULT NULL;

UPDATE CART SET DEL_YN = 0 WHERE DEL_YN IS NULL;
ALTER TABLE CART MODIFY DEL_YN NUMBER(1) DEFAULT 0;

CREATE SEQUENCE RECEIPT_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM PRODUCT;
SELECT * FROM CATEGORY;
SELECT * FROM S_CATEGORY;
SELECT * FROM CART;
DESC CART;

ALTER TABLE CART ADD DEL_YN NUMBER(1) DEFAULT NULL;
ALTER TABLE CART ADD RECEIPT_NO NUMBER DEFAULT NULL;
ALTER TABLE CART ADD PAYMENT_DAY DATE DEFAULT NULL;
COMMIT;

ROLLBACK;

DELETE FROM CART;

SELECT * FROM PRODUCT;
ALTER TABLE CART MODIFY P_NO NUMBER;
ALTER TABLE CART MODIFY CART_ITEM_NO DEFAULT CART_SEQ.NEXTVAL;
SELECT A.P_NAME, SUM(A.P_QTY) FROM PRODUCT A, PRODUCT B GROUP BY A.P_NAME;

SELECT P_NAME, SUM(P_QTY) FROM PRODUCT GROUP BY P_NAME;

SELECT P_NAME FROM PRODUCT WHERE P_NO = 2;
SELECT C.CART_ITEM_NO, P.P_NAME, C.P_QTY, C.P_PRICE, C.TOTAL_PRICE FROM CART C JOIN PRODUCT P ON P.P_NO = C.P_NO;

SELECT ROWNUM, C.C_NO, S.S_NO, P.P_NAME, P.P_QTY, P.P_EXPDATE FROM PRODUCT P, CATEGORY C, S_CATEGORY S WHERE P.P_SUBCATEGORY_NO = S.S_NO AND S.C_NO = C.C_NO ORDER BY S.S_NO;

SELECT * FROM PRODUCT ORDER BY P_SUBCATEGORY_NO;

SELECT P.P_NO, P.P_NAME, P.P_PRICE, P.P_QTY, P.P_EXPDATE, C.C_NAME, S.S_NAME FROM PRODUCT P, S_CATEGORY S, "CATEGORY" C
WHERE P.P_SUBCATEGORY_NO = S.S_NO
AND S.C_NO = C.C_NO ORDER BY P.P_NO;

SELECT * FROM PRODUCT ORDER BY P_CATEGORY_NO;

SELECT * FROM CART;