CREATE TABLE SALES(
    RECEIPT_NO NUMBER PRIMARY KEY
    P_NO NUMBER NOT NULL,
    SALES_QTY NUMBER NOT NULL,
    
);
ALTER TABLE SALES ADD CONSTRAINT FOREIGN KEY(P_NO) REFERENCES PRODUCT(P_NO);
    
CREATE SEQUENCE SALES_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM PRODUCT;