WHERE COMMISSION_PCT IS NOT NULL;

-- 사번 기준 내림차순 정렬, 연봉 기준 오름차순 정렬/
SELECT JOB_ID, SALARY FROM EMPLOYEES ORDER BY JOB_ID DESC, SALARY ASC;
-- 가상테이블 -> 진짜테이블(테이블 구성 ; 인스턴스 1개, 컬럼명 2개)
SELECT 24+34 AS RESLUT FROM DUAL;
-- 부서별 총 급여 출력
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),-2) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING SUM(SALARY) >= 50000 AND DEPARTMENT_ID = 100;
