-- DEPARTMENT_ID, 부서 평균, 부서 합계, 부서 인원수를 DEPARTMENT_ID 기준으로 오름차순 정렬하여 출력(단, MANAGER_ID가 NOT NULL 인 사원만)
SELECT DEPARTMENT_ID 부서, ROUND(AVG(SALARY)) 급여평균, SUM(SALARY) 급여합계, COUNT(*) 인원수 FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT NULL GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

-- 
DECLARE
    TYPE FIRST_NAME_TABLE_TYPE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY BINARY_INTEGER; 
    TYPE JOB_ID_TABLE_TYPE IS TABLE OF EMPLOYEES.JOB_ID%TYPE INDEX BY BINARY_INTEGER;
    TYPE EMPLOYEE_ID_TABLE_TYPE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;
    TYPE MANAGER_ID_TABLE_TYPE IS TABLE OF EMPLOYEES.MANAGER_ID%TYPE INDEX BY BINARY_INTEGER;
    -- 변수(배열타입을 적용) 정수형배열(1), 문자열배열(2개)
    NAME_TABLE FIRST_NAME_TABLE_TYPE;
    JOB_TABLE JOB_ID_TABLE_TYPE;
    EMPNO_TABLE EMPLOYEE_ID_TABLE_TYPE;
     MANAGER_TABLE MANAGER_ID_TABLE_TYPE;
    I BINARY_INTEGER := 0; 
BEGIN
    FOR K IN (SELECT FIRST_NAME, JOB_ID, EMPLOYEE_ID, MANAGER_ID FROM EMPLOYEES)  LOOP
        I := I + 1; 
        NAME_TABLE(I) := K.FIRST_NAME; 
        JOB_TABLE(I) := K.JOB_ID; 
        EMPNO_TABLE(I) := K.EMPLOYEE_ID; 
        MANAGER_TABLE(I) := K.MANAGER_ID;

    END LOOP;

    FOR J IN 1..I LOOP
        IF(MANAGER_TABLE(I) = '' OR MANAGER_TABLE(I) IS NULL ) THEN
            MANAGER_TABLE(I):=0;
        END IF; 
        DBMS_OUTPUT.PUT_LINE('1.FIRST_NAME = 'NAME_TABLE(J)  ' 2.JOB_ID ='  JOB_TABLE(J)' 3.EMP_NO =' EMPNO_TABLE(J) ' 3.MANAGER =' ||MANAGER_TABLE(J)); 
    END LOOP; 
END;
/

-- 