DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
    P_NO NUMBER,
    P_NAME VARCHAR2(30) NOT NULL,
    P_PRICE NUMBER NOT NULL,
    P_QTY NUMBER NOT NULL,
    P_EXPDATE DATE,
    P_SUBCATEGORY_NO NUMBER NOT NULL
);

DELETE FROM PRODUCT;

ALTER TABLE PRODUCT ADD CONSTRAINTS PRODUCT_PK PRIMARY KEY(P_NO);
ALTER TABLE PRODUCT ADD CONSTRAINTS PRODUCT_FK2 FOREIGN KEY(P_SUBCATEGORY_NO) REFERENCES S_CATEGORY(S_NO);

CREATE SEQUENCE PRODUCT_SEQ
    START WITH 1
    INCREMENT BY 1;
    
DROP SEQUENCE PRODUCT_SEQ;

INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '빼빼로', 2000, 100, '2026-12-31', 1);

COMMIT;

ROLLBACK;

SELECT P.P_NO, P.P_NAME, p.p_PRICE, P.P_QTY, P.P_EXPDATE, C.C_NO,C.C_NAME, S.S_NO, S.S_NAME
FROM PRODUCT P, S_CATEGORY S, "CATEGORY" C 
WHERE P.P_SUBCATEGORY_NO = S.S_NO 
AND S.C_NO = C.C_NO;


DROP TABLE CATEGORY;
CREATE TABLE CATEGORY(
    C_NO NUMBER NOT NULL PRIMARY KEY,
    C_NAME VARCHAR2(30)
);
DROP SEQUENCE CATEGORY_SEQ;
CREATE SEQUENCE CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1;

INSERT INTO CATEGORY VALUES(CATEGORY_SEQ.NEXTVAL, '생활용품');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQ.NEXTVAL, '식품');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQ.NEXTVAL, '전자제품');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQ.NEXTVAL, '음료');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQ.NEXTVAL, '의약외품');


SELECT * FROM CATEGORY;
DROP TABLE S_CATEGORY;
CREATE TABLE S_CATEGORY(
    S_NO NUMBER NOT NULL PRIMARY KEY,
    C_NO NUMBER NOT NULL,
    S_NAME VARCHAR2(30)
);
ALTER TABLE S_CATEGORY ADD CONSTRAINTS S_CATEGORY_FK1 FOREIGN KEY(C_NO) REFERENCES "CATEGORY"(C_NO);

DROP SEQUENCE S_CATEGORY_SEQ;
CREATE SEQUENCE S_CATEGORY_SEQ
START WITH 1
INCREMENT BY 1;

SELECT S.S_NO, C.C_NAME, S.S_NAME 
FROM S_CATEGORY S JOIN "CATEGORY" C ON S.C_NO = C.C_NO
WHERE C.C_NO = (SELECT C1.C_NO FROM "CATEGORY" C1 WHERE C1.C_NAME = '음료');

INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 2, '과자');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 2, '냉동식품');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 2, '빵');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 2, '즉석식품');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 2, '라면');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 2, '장/소스');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 4, '생수');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 4, '탄산음료');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 4, '에너지드링크');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 4, '주류');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 4, '유제품');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 1, '위생용품');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 1, '욕실용품');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 1, '청소/세탁');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 1, '문구류');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 5, '파스');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 5, '밴드');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 5, '소독제');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 3, '충전기');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 3, '이어폰');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 3, '배터리');
INSERT INTO S_CATEGORY VALUES (S_CATEGORY_SEQ.NEXTVAL, 3, '컴퓨터용품');

SELECT * FROM PRODUCT;
SELECT * FROM CATEGORY;
SELECT * FROM S_CATEGORY;

SELECT * FROM S_CATEGORY ORDER BY S_NO;