CREATE TABLE MEMBER(
    NO NUMBER,
    ID VARCHAR2(100) NOT NULL,
    PWD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE MEMBER ADD CONSTRAINTS MEMBER_PK PRIMARY KEY (NO);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MEMBER;