CREATE TABLE CODE_GROUP(
    GROUP_CODE VARCHAR2(3) NOT NULL,
    GROUP_NAME VARCHAR2(30) NOT NULL,
    USE_YN VARCHAR2(1) DEFAULT 'Y',
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (GROUP_CODE)
);
        
SELECT * FROM CODE_GROUP;
DELETE FROM CODE_GROUP;
COMMIT;

CREATE TABLE CODE_DETAIL(
    GROUP_CODE VARCHAR2(3) NOT NULL,
    CODE_VALUE VARCHAR2(3) NOT NULL,
    CODE_NAME VARCHAR2(30) NOT NULL,
    SORT_SEQ NUMBER NOT NULL,
    USE_YN VARCHAR2(1) DEFAULT 'Y',
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (GROUP_CODE, CODE_VALUE)
);

CREATE TABLE MEMBER(
    USER_NO NUMBER(5) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    USER_PW VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    JOB VARCHAR2(3) DEFAULT '00',
    COIN NUMBER(10) DEFAULT 0,
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE DEFAULT SYSDATE,
    ENABLED VARCHAR2(1) DEFAULT '1',
    PRIMARY KEY (USER_NO)
);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE MEMBER_AUTH(
    USER_NO NUMBER(5) NOT NULL,
    AUTH VARCHAR2(50) NOT NULL
);

ALTER TABLE MEMBER_AUTH ADD CONSTRAINT FK_MEMBER_AUTH_USER_NO 
FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO);

DELETE FROM MEMBER;
DELETE FROM CODE_DETAIL;
DELETE FROM MEMBER_AUTH;

SELECT * FROM MEMBER_AUTH;
SELECT * FROM MEMBER;
SELECT * FROM CODE_DETAIL;
