SELECT * FROM TAB;

--테이블 복사
CREATE TABLE EMPLOYEES2 AS SELECT * FROM EMPLOYEES;

DESC EMPLOYEES2;

-- AGE 추가
ALTER TABLE EMPLOYEES2 ADD AGE NUMBER(3) CHECK (AGE BETWEEN 0 AND 150);

-- AGE 자릿수 4로 변경
ALTER TABLE EMPLOYEES2 MODIFY AGE NUMBER(4);

-- AGE 삭제
ALTER TABLE EMPLOYEES2 DROP COLUMN AGE;

--FIRST_NAME VARCHAR2(20) = VARCHAR2(10)
ALTER TABLE EMPLOYEES2
MODIFY FIRST_NAME VARCHAR2(22);

CREATE TABLE EMPLOYEES3 AS SELECT * FROM EMPLOYEES2;

DESC EMPLOYEES3;

SELECT * FROM RECYCLEBIN;
-- 휴지통 복구
FLASHBACK TABLE EMPLOYEE2 TO BEFORE DROP;
-- 휴지통 비우기
PURGE RECYCLEBIN;
-- 컬럼사이즈 줄여서 복사하는 방법
CREATE TABLE TESTA(NAME CHAR(10) NOT NULL, AGE NUMBER(3) NOT NULL);
INSERT INTO TESTA VALUES('1234567890',34);
INSERT INTO TESTA VALUES('12345678',60);
SELECT * FROM TESTA;

CREATE TABLE TESTB(NAME2 CHAR(6) NOT NULL, AGE2 NUMBER(3) NOT NULL);
DESC TESTB;

INSERT INTO TESTB(NAME2, AGE2) SELECT SUBSTR(NAME,1,6), AGE FROM TESTA;

SELECT * FROM TESTB;

RENAME EMPLOYEES2 TO EMPLOYEES4;

--테이블 설계 EMP02(번호, 이름, 직업, 부서) 제약조건 NULL
CREATE TABLE EMP02(
    EMP_NO NUMBER(10),
    EMP_NAME VARCHAR2(10),
    EMP_JOB VARCHAR2(10),
    DEP_ID VARCHAR2(10)
);
INSERT INTO EMP02 VALUES(1,'가가가','목수',NULL);
TRUNCATE TABLE EMP02;

SELECT * FROM EMP02;
-- DEP_ID NOT NULL 제약조건 설정
ALTER TABLE EMP02 MODIFY DEP_ID VARCHAR2(10) NOT NULL;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP02';

CREATE TABLE EMP05(
    EMP_NO NUMBER(10),
    EMP_NAME VARCHAR2(10),
    EMP_JOB VARCHAR2(10),
    DEP_ID VARCHAR2(10)
);

-- UNIQUE 제약조건 설정(EMP_NAME)
ALTER TABLE EMP05 MODIFY EMP_NAME VARCHAR(10) UNIQUE;


-- Q. 이미 존재하는 EMP01 테이블에 입사일 칼럼(CREDATE)을 날짜형으로 추가
ALTER TABLE EMP01 ADD(CREDATE DATE);

-- Q. 고객 테이블 생성을 위한 필드 설정
CREATE TABLE 고객(
    고객코드 CHAR(7) NOT NULL,
    고객명 VARCHAR2(10) NOT NULL,
    성별 CHAR(1) NOT NULL,
    생일 CHAR(8) NOT NULL,
    전화번호 VARCHAR2(16),
    이메일 VARCHAR2(30),
    누적포인트 NUMBER(10,0)
);
SELECT * FROM 고객;

ALTER TABLE 고객 ADD CONSTRAINT 고객_PK PRIMARY KEY(고객코드);
ALTER TABLE 고객 MODIFY 누적포인트 NUMBER(10,0) DEFAULT 0;
ALTER TABLE 고객 ADD 등록일시 CHAR(14);

-- Q. 학생성적 테이블 생성
CREATE TABLE 학생성적(
    학번 NUMBER(10,0) NOT NULL,
    이름 VARCHAR(6) NOT NULL,
    국어 NUMBER(3) DEFAULT 0 NOT NULL,
    영어 NUMBER(3) DEFAULT 0 NOT NULL,
    수학 NUMBER(3) DEFAULT 0 NOT NULL
);
ALTER TABLE 학생성적 ADD 학과코드 VARCHAR2(10);
ALTER TABLE 학생성적 ADD CONSTRAINT 학과코드_FK FOREIGN KEY(학과코드) REFERENCES 학과(학과코드);
ALTER TABLE 학생성적 MODIFY 이름 VARCHAR(18);

SELECT * FROM 학생성적;

INSERT INTO 학생성적(학번, 이름, 국어, 영어, 수학, 학과코드) VALUES(202501, '가가가', 100, 90, 80, '0001');
INSERT INTO 학생성적(학번, 이름, 국어, 영어, 수학, 학과코드) VALUES(202502, '나나나', 77, 66, 55, '0002');

CREATE TABLE 학과(
    학과코드 VARCHAR(10) NOT NULL,
    학과명 VARCHAR(10) NOT NULL
);

ALTER TABLE 학과 ADD CONSTRAINT 학과_PK PRIMARY KEY(학과코드);

INSERT INTO 학과(학과코드, 학과명) VALUES('0001', '탑');
INSERT INTO 학과(학과코드, 학과명) VALUES('0002', '티모');
INSERT INTO 학과(학과코드, 학과명) VALUES('0003', '화이팅');

SELECT * FROM 학과;