SELECT * FROM TAB;

-- 테이블 구조 확인
DESCRIBE TAB;
DESC EMPLOYEES;

-- EMPLOYEES 테이블 전체내용
SELECT * FROM EMPLOYEES;

-- ID, NAME, EMAIL만 출력
SELECT EMPLOYEE_ID AS 아이디, FIRST_NAME AS 이름, LAST_NAME AS 성, EMAIL AS 이메일 FROM EMPLOYEES;
SELECT EMPLOYEE_ID  아이디, FIRST_NAME  이름, LAST_NAME  성, EMAIL  이메일 FROM EMPLOYEES;
SELECT EMPLOYEE_ID AS "회사 아이디", FIRST_NAME AS "회사 이름", LAST_NAME AS "회사 성", EMAIL AS "회사 이메일" FROM EMPLOYEES;

-- ID가 107번인 사원만 출력
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 107;

-- ID가 107 ~ 110번인 사원만 출력
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID >= 107 AND EMPLOYEE_ID <= 110;

-- FIRST_NAME이 D로 시작하는 사원만 출력 (2번째 글자 = '_D%', 중간 글자 = '%D%', 마지막 글자 = '%d')
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%d';