CREATE TABLE ITEM(
    ID NUMBER(5),
    NAME VARCHAR2(20),
    PRICE NUMBER(6),
    DESCRIPTION VARCHAR2(50),
    PICTURE_URL VARCHAR2(200)
);

ALTER TABLE ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY(ID);
ALTER TABLE ITEM MODIFY NAME VARCHAR2(50);

CREATE SEQUENCE ITEM_SEQ
START WITH 1
INCREMENT BY 1;

DESC ITEM;

SELECT * FROM ITEM;