CREATE TABLE BOARD (
    BOARD_NO NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(3000),
    WRITER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (BOARD_NO)
);

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MEMBER_AUTH;

SELECT * FROM MEMBER;

UPDATE MEMBER_AUTH SET AUTH = 'ROLE_ADMIN' WHERE USER_NO = 2;

COMMIT;

CREATE TABLE PERSISTENT_LOGINS(
    USERNAME VARCHAR2(64) NOT NULL,
    SERIES VARCHAR2(64) NOT NULL,
    TOKEN VARCHAR2(64) NOT NULL,
    LAST_USED DATE NOT NULL,
    PRIMARY KEY (SERIES)
);