CREATE TABLE DEPT01(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13),
    CONSTRAINT DEPT01_PK PRIMARY KEY(DEPTNO)
    );
    INSERT INTO DEPT01 VALUES(10, 'ACCOUNTING', 'NEW YORK');
    INSERT INTO DEPT01 VALUES(20, 'RESEARCH', 'DALLAS');
    SELECT * FROM DEPT01;
    
    INSERT INTO DEPT01 VALUES(30, 'DEVELOPMENT', 'KOREA');
    DELETE FROM DEPT01 WHERE DEPTNO = 10;
    
    
    CREATE TABLE EMP01(
        EMPNO NUMBER(4),
        ENAME VARCHAR2(10) NOT NULL, 
        JOB VARCHAR2(9),
        DEPTNO NUMBER(4), 
        PRIMARY KEY(EMPNO),
        FOREIGN KEY(DEPTNO) REFERENCES DEPT01(DEPTNO)
    );
      
    INSERT INTO EMP01 VALUES(7499, 'ALLEN', 'SALESMAN', 10);
    INSERT INTO EMP01 VALUES(7369, 'SMITH', 'CLERK', 20);
    SELECT * FROM EMP01;
    UPDATE EMP01 SET DEPTNO = 20 WHERE EMPNO = 7499;
    DELETE FROM EMP01 WHERE EMPNO = 7369;
    
    -- CROSS JOIN
    SELECT * FROM EMPLOYEES;
    SELECT * FROM DEPARTMENTS;
    SELECT * FROM EMPLOYEES, DEPARTMENTS;
    
    -- INNER JOIN(PK : 부모, 참조 = FK : 자식, 기본, 주)
    SELECT * FROM EMPLOYEES;
    SELECT * FROM DEPARTMENTS;
    SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEES';
    SELECT E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM EMPLOYEES E, DEPARTMENTS D
    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;
    
    CREATE TABLE SALARYGRADE
        (GRADE NUMBER(2),
        MINSALARY NUMBER(7),
        MAXSALARY NUMBER(10)
        );
    
    INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(1, 2000, 3000);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(2, 3001, 4500);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(3, 4501, 6000);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(4, 6001, 8000);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(5, 8001, 10000);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(6, 10001, 13000);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(7, 13001, 20000);
INSERT INTO SALARYGRADE (GRADE, MINSALARY, MAXSALARY) VALUES(8, 20001, 30000);
    
    SELECT E.FIRST_NAME, E.SALARY, S.GRADE 등급 FROM EMPLOYEES E, SALARYGRADE S
    WHERE E.SALARY BETWEEN S.MINSALARY AND S.MAXSALARY; 
    
-- 2007년 상반기에 입사한 사원 조회
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND (HIRE_DATE BETWEEN '2007/01/01' AND '2007/06/30');

-- SELF JOIN (1개의 테이블을 2개로 만들어 조인한다고 생각)
SELECT * FROM EMPLOYEES;
SELECT E2.EMPLOYEE_ID 사원아이디, E2.FIRST_NAME 사원이름, E2.SALARY 사원월급, E1.MANAGER_ID 상사아이디, E1.FIRST_NAME 상사이름, E1.SALARY 상사월급 
FROM EMPLOYEES E1, EMPLOYEES E2 
WHERE E1.EMPLOYEE_ID = E2.MANAGER_ID;

-- OUTER JOIN (ANSI RIGHT OUTER JOIN)
SELECT E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- OUTER JOIN (ANSI LEFT OUTER JOIN)
SELECT E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- ROWNUM (번호 자동 설정)
SELECT * FROM EMPLOYEES WHERE ROWNUM <= 10;

SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT FIRST_NAME, SALARY FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <=10;