CREATE TABLE MEMBER(
    NO NUMBER,
    ID VARCHAR2(50) NOT NULL, 
    PW VARCHAR2(50) NOT NULL, 
    NAME VARCHAR2(100) NOT NULL, 
    COIN NUMBER(10) DEFAULT 0,
    REG_DATE DATE DEFAULT SYSDATE, 
    UPD_DATE DATE DEFAULT SYSDATE, 
    ENABLED CHAR(1) DEFAULT '1'
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(NO);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE MEMBER_AUTH(
    NO NUMBER NOT NULL,
    AUTH VARCHAR2(50) NOT NULL
);

ALTER TABLE MEMBER_AUTH ADD CONSTRAINT MEMBER_AUTH_NO_FK FOREIGN KEY(NO) REFERENCES MEMBER(NO);

CREATE TABLE MEMBER_EMAIL(
    NO NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL CHECK(REGEXP_LIKE(EMAIL, '^[a-zA-Z0-9가-힣._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'))
);

ALTER TABLE MEMBER_EMAIL ADD CONSTRAINT MEMBER_EMAIL_NO_FK FOREIGN KEY(NO) REFERENCES MEMBER(NO);

INSERT INTO MEMBER_EMAIL(NO, EMAIL) VALUES(1, 'TEST@TEST.COM');

		SELECT M.NO, ID, PW, NAME,
		REG_DATE, UPD_DATE, A.AUTH, E.EMAIL
		FROM MEMBER M LEFT OUTER JOIN
		MEMBER_AUTH A ON M.NO = A.NO
		JOIN MEMBER_EMAIL E ON A.NO = E.NO WHERE
		M.NO = E.NO AND E.EMAIL != 'example@email.com';

SELECT M.NO, ID, PW, NAME,
		REG_DATE, UPD_DATE, A.AUTH, E.EMAIL 
        FROM MEMBER M LEFT OUTER JOIN MEMBER_AUTH A ON M.NO = A.NO 
        JOIN MEMBER_EMAIL E ON A.NO = E.NO WHERE M.NO = 1;

DESC MEMBER;
DESC MEMBER_AUTH;

INSERT INTO MEMBER(NO, ID, PW, NAME) VALUES(MEMBER_SEQ.NEXTVAL, '티모', '핫둘셋넷', '이게몽가티몽가');
INSERT INTO MEMBER_AUTH(NO, AUTH) VALUES(1, 'ADMIN');

SELECT M.NO, ID, PW, NAME, REG_DATE, UPD_DATE, AUTH FROM MEMBER M LEFT OUTER JOIN MEMBER_AUTH A ON M.NO = A.NO
WHERE M.NO = 7;

SELECT NO, ID, PW, NAME, REG_DATE FROM MEMBER ORDER BY REG_DATE DESC;
UPDATE MEMBER SET NAME = '테쓰뜽' WHERE NO = 6;
DELETE FROM MEMBER_AUTH WHERE NO = 6;
DELETE FROM MEMBER WHERE NO = 6;

ROLLBACK;

SELECT * FROM MEMBER;
SELECT * FROM MEMBER_AUTH;
SELECT * FROM MEMBER_EMAIL;

DELETE FROM MEMBER;

COMMIT;

SELECT * FROM BOARD;
DESC BOARD;