CREATE TABLE AOPBOARD(
    NO NUMBER,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(1000) NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY(NO)
);

CREATE SEQUENCE AOPBOARD_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM AOPBOARD;

DELETE FROM MEMBER;
DELETE FROM MEMBER_EMAIL;
DELETE FROM MEMBER_AUTH;

COMMIT;

CREATE TABLE AOPMEMBER(
    NO NUMBER,
    ID VARCHAR2(50) NOT NULL,
    PW VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY(NO)
);

CREATE SEQUENCE AOPMEMBER_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM AOPMEMBER;