CREATE TABLE MYBATISBOARD(
    NO NUMBER,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(500) NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE MYBATISBOARD ADD CONSTRAINTS MYBATISBOARD_PK PRIMARY KEY (NO);

CREATE SEQUENCE MYBATISBOARD_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MYBATISBOARD;

CREATE TABLE MYBATISMEMBER(
    NO NUMBER,
    ID VARCHAR2(100) NOT NULL,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE MYBATISMEMBER ADD CONSTRAINTS MYBATISMEMBER_PK PRIMARY KEY (NO);

CREATE SEQUENCE MYBATISMEMBER_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MYBATISMEMBER;